### ISSUE TITLE
Migrate to pnpm workspaces

### ISSUE THREAD

**Issue by guillaumebriday** [stimulus-components/stimulus-components#103]
## Todo

- [x] Move to vitest
- [x] move to redirects and remove netlify build
- [x] Redirects demo to docs
- [x] Change homepage in package.json
- [x] Remove yarn references
- [x] Configure workflows
- [x] Better prettier configuration
- [x] npmignore on packages
- [x] README contribution section

## Redirects

- [x] Chartjs
- [ ] Rails Nested Form
- [x] Sortable
- [x] Popover
- [x] Prefetch
- [x] Content Loader
- [x] Glow
- [x] Remote Rails
- [x] Reveal Controller
- [x] Textarea Autogrow
- [x] Animated Number
- [x] Auto Submit
- [x] Carousel
- [x] Color Picker
- [x] Dialog
- [x] Lightbox
- [x] Notification
- [x] Password Visibility
- [x] Places Autocomplete
- [x] Read More
- [x] Scroll Progress
- [x] Scroll Reveal
- [x] Scroll To
- [x] Sound
- [x] Timeago
- [x] Dropdown
- [x] Clipboard
- [x] Checkbox Select All
- [x] Character Counter

## Packages to move

- [x] Popover
- [x] Prefetch
- [x] Content Loader
- [x] Glow
- [x] Remote Rails
- [x] Reveal Controller
- [x] Textarea Autogrow
- [x] Animated Number
- [x] Auto Submit
- [x] Carousel
- [x] Chartjs
- [x] Color Picker
- [x] Dialog
- [x] Lightbox
- [x] Notification
- [x] Password Visibility
- [x] Places Autocomplete
- [x] Rails Nested Form
- [x] Read More
- [x] Scroll Progress
- [x] Scroll Reveal
- [x] Scroll To
- [x] Sortable
- [x] Sound
- [x] Timeago
- [x] Dropdown
- [x] Clipboard
- [x] Checkbox Select All
- [x] Character Counter
